# Generated by Django 2.2.7 on 2020-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать ?'),
        ),
        migrations.AddField(
            model_name='news',
            name='main_img',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка Новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='show_at_index',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(null=True, upload_to='news/', verbose_name='Картинка превью'),
        ),
    ]
