# Generated by Django 2.1.4 on 2020-07-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_feedback_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
