# Generated by Django 2.1.4 on 2020-07-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
