# Generated by Django 3.0.7 on 2020-06-11 17:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Название пункта меню')),
                ('icon', models.ImageField(null=True, upload_to='menu_icons/', verbose_name='Иконка')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка(без указания домена)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать ?')),
            ],
            options={
                'verbose_name': 'Пункт левого меню',
                'verbose_name_plural': 'Пункты левого меню',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('is_home_page', models.BooleanField(default=False, verbose_name='Главная страница ?')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
        migrations.CreateModel(
            name='RightMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Название пункта меню')),
                ('icon', models.ImageField(null=True, upload_to='menu_icons/', verbose_name='Иконка')),
                ('custom_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка(без указания домена)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать ?')),
                ('static_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.StaticPage', verbose_name='Ссылка на статическую страницу')),
            ],
            options={
                'verbose_name': 'Пункт правого меню',
                'verbose_name_plural': 'Пункты правого меню',
            },
        ),
    ]
