# Generated by Django 3.0.7 on 2020-06-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_content', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leftmenuitem',
            old_name='url',
            new_name='custom_url',
        ),
        migrations.AddField(
            model_name='leftmenuitem',
            name='event_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events_content.EventPage', verbose_name='Ссылка на мероприятие'),
        ),
    ]
