# Generated by Django 3.0.7 on 2020-06-11 20:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200611_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='auto_slug',
            field=models.BooleanField(default=True, verbose_name='Создать ЧПУ ?'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной контент'),
        ),
    ]
