# Generated by Django 3.0.7 on 2020-06-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200611_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightmenuitem',
            name='icon',
        ),
        migrations.AddField(
            model_name='leftmenuitem',
            name='icon',
            field=models.ImageField(null=True, upload_to='menu_icons/', verbose_name='Иконка'),
        ),
    ]
