# Generated by Django 3.0.7 on 2020-06-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200611_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftmenuitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rightmenuitem',
            name='title',
        ),
        migrations.AddField(
            model_name='rightmenuitem',
            name='is_callback',
            field=models.BooleanField(default=False, verbose_name='Кнопка заказать звонок ?'),
        ),
    ]
