# Generated by Django 2.2.7 on 2020-06-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_content', '0002_auto_20200611_2306'),
        ('pages', '0006_auto_20200611_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='menu_icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название пункта')),
                ('custom_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка(без указания домена)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать ?')),
                ('event_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events_content.EventPage', verbose_name='Ссылка на мероприятие')),
            ],
            options={
                'verbose_name': 'Пункт верхнего меню',
                'verbose_name_plural': 'Пункты верхнего меню',
            },
        ),
    ]
