# Generated by Django 2.2.7 on 2020-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200618_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightmenuitem',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название пункта (указывать если используется Ссылка(без указания домена))'),
        ),
    ]
