# Generated by Django 2.2.7 on 2020-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rightmenuitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightmenuitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название пункта (указывать если используется Ссылка(без указания домена))'),
        ),
    ]
