# Generated by Django 2.2.7 on 2020-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отображать ?'),
        ),
    ]
