# Generated by Django 2.2.7 on 2020-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_img',
            field=models.ImageField(null=True, upload_to='blog/', verbose_name='Картинка статьи'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(null=True, upload_to='blog/', verbose_name='Картинка превью'),
        ),
    ]
