# Generated by Django 2.1.4 on 2020-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='От')),
                ('preview', models.ImageField(null=True, upload_to='blog/', verbose_name='Картинка превью')),
                ('main_img', models.ImageField(null=True, upload_to='blog/', verbose_name='Картинка статьи')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Основной контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать ?')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
