# Generated by Django 2.1.4 on 2020-07-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='main_img',
        ),
    ]
