# Generated by Django 2.2.7 on 2020-06-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200618_0850'),
        ('events_content', '0002_auto_20200611_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='top_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.TopMenuItem', verbose_name='Показывать в меню'),
        ),
    ]
