# Generated by Django 2.2.7 on 2020-06-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_content', '0003_eventpage_top_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='top_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_items', to='pages.TopMenuItem', verbose_name='Показывать в меню'),
        ),
    ]
