# Generated by Django 2.1.4 on 2020-07-06 12:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_content', '0004_auto_20200618_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEventPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('auto_slug', models.BooleanField(default=True, verbose_name='Создать ЧПУ ?')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основной контент')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Описание страницы SEO')),
                ('page_keywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
