# Generated by Django 2.1.4 on 2020-07-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_content', '0005_subeventpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubEventPage',
        ),
    ]
