# Generated by Django 2.1.4 on 2020-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200618_1112'),
        ('events_content', '0006_delete_subeventpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='top_menu',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='top_menu',
            field=models.ManyToManyField(blank=True, related_name='event_items', to='pages.TopMenuItem', verbose_name='Показывать в меню'),
        ),
    ]
